import type { IconCategory, IconDefinition, TemplateName } from './types.ts';

function icon(
  id: string,
  title: string,
  description: string,
  category: IconCategory,
  template: TemplateName,
  seed: number,
): IconDefinition {
  return { id, title, description, category, template, seed };
}

/** 扩展批次：246 → 500，共 254 个 */
export const EXPANSION_CATALOG: IconDefinition[] = [
  icon('dna-helix-1', 'DNA 双螺旋', '碱基配对双链盘绕', 'biology', 'dna-helix', 364),
  icon('dna-helix-2', '基因双链', '碱基配对双链盘绕', 'biology', 'dna-helix', 365),
  icon('dna-helix-3', '核酸螺旋', '碱基配对双链盘绕', 'biology', 'dna-helix', 366),
  icon('dna-replicate-1', 'DNA 复制', '双链解旋逐段复制', 'biology', 'dna-replicate', 367),
  icon('dna-replicate-2', '半保留复制', '双链解旋逐段复制', 'biology', 'dna-replicate', 368),
  icon('dna-replicate-3', '复制叉推进', '双链解旋逐段复制', 'biology', 'dna-replicate', 369),
  icon('rna-transcribe-1', 'RNA 转录', 'DNA 模板合成 RNA', 'biology', 'rna-transcribe', 370),
  icon('rna-transcribe-2', 'mRNA 合成', 'DNA 模板合成 RNA', 'biology', 'rna-transcribe', 371),
  icon('rna-transcribe-3', '转录延伸', 'DNA 模板合成 RNA', 'biology', 'rna-transcribe', 372),
  icon('protein-fold-1', '蛋白质折叠', '氨基酸链折叠成功能构象', 'biology', 'protein-fold', 373),
  icon('protein-fold-2', '多肽折叠', '氨基酸链折叠成功能构象', 'biology', 'protein-fold', 374),
  icon('protein-fold-3', '结构域形成', '氨基酸链折叠成功能构象', 'biology', 'protein-fold', 375),
  icon('cell-membrane-1', '细胞膜通道', '膜蛋白通道开闭转运', 'biology', 'cell-membrane', 376),
  icon('cell-membrane-2', '离子通道', '膜蛋白通道开闭转运', 'biology', 'cell-membrane', 377),
  icon('cell-membrane-3', '膜运输', '膜蛋白通道开闭转运', 'biology', 'cell-membrane', 378),
  icon('photosynthesis-1', '光合作用', '光能转化学能循环', 'biology', 'photosynthesis-lab', 379),
  icon('photosynthesis-2', '光反应', '光能转化学能循环', 'biology', 'photosynthesis-lab', 380),
  icon('photosynthesis-3', '碳固定', '光能转化学能循环', 'biology', 'photosynthesis-lab', 381),
  icon('neuron-pulse-1', '动作电位', '膜电位去极化复极化', 'biology', 'neuron-pulse', 382),
  icon('neuron-pulse-2', '神经冲动', '膜电位去极化复极化', 'biology', 'neuron-pulse', 383),
  icon('neuron-pulse-3', '轴突传导', '膜电位去极化复极化', 'biology', 'neuron-pulse', 384),
  icon('heartbeat-ecg-1', '心电图', '心电 QRS 周期性搏动', 'biology', 'heartbeat-ecg', 385),
  icon('heartbeat-ecg-2', '心室收缩', '心电 QRS 周期性搏动', 'biology', 'heartbeat-ecg', 386),
  icon('heartbeat-ecg-3', '脉搏节律', '心电 QRS 周期性搏动', 'biology', 'heartbeat-ecg', 387),
  icon('mitosis-1', '有丝分裂', '细胞分裂周期推进', 'biology', 'mitosis-split', 388),
  icon('mitosis-2', '染色体分离', '细胞分裂周期推进', 'biology', 'mitosis-split', 389),
  icon('mitosis-3', '胞质分裂', '细胞分裂周期推进', 'biology', 'mitosis-split', 390),
  icon('virus-infect-1', '病毒感染', '病毒附着穿入复制', 'biology', 'virus-infect', 391),
  icon('virus-infect-2', '病毒侵染', '病毒附着穿入复制', 'biology', 'virus-infect', 392),
  icon('virus-infect-3', '宿主入侵', '病毒附着穿入复制', 'biology', 'virus-infect', 393),
  icon('enzyme-bind-1', '酶促反应', '锁钥结合降低能垒', 'biology', 'enzyme-binding', 394),
  icon('enzyme-bind-2', '酶底物复合', '锁钥结合降低能垒', 'biology', 'enzyme-binding', 395),
  icon('enzyme-bind-3', '催化循环', '锁钥结合降低能垒', 'biology', 'enzyme-binding', 396),
  icon('blood-flow-1', '血液循环', '心脏泵血循环全身', 'biology', 'blood-flow', 397),
  icon('blood-flow-2', '动脉血流', '心脏泵血循环全身', 'biology', 'blood-flow', 398),
  icon('blood-flow-3', '毛细血管交换', '心脏泵血循环全身', 'biology', 'blood-flow', 399),
  icon('muscle-contract-1', '肌肉收缩', '肌动肌球蛋白相对滑动', 'biology', 'muscle-contract', 400),
  icon('muscle-contract-2', '肌丝滑行', '肌动肌球蛋白相对滑动', 'biology', 'muscle-contract', 401),
  icon('muscle-contract-3', '肌节缩短', '肌动肌球蛋白相对滑动', 'biology', 'muscle-contract', 402),
  icon('bacteria-divide-1', '细菌分裂', '原核细胞一分为二', 'biology', 'bacteria-divide', 403),
  icon('bacteria-divide-2', '二分裂', '原核细胞一分为二', 'biology', 'bacteria-divide', 404),
  icon('bacteria-divide-3', '菌群增殖', '原核细胞一分为二', 'biology', 'bacteria-divide', 405),
  icon('osmosis-1', '渗透作用', '水沿浓度梯度跨膜', 'biology', 'osmosis-flow', 406),
  icon('osmosis-2', '水分子跨膜', '水沿浓度梯度跨膜', 'biology', 'osmosis-flow', 407),
  icon('osmosis-3', '渗透平衡', '水沿浓度梯度跨膜', 'biology', 'osmosis-flow', 408),
  icon('bubble-sort-1', '冒泡排序', '相邻元素比较交换', 'cs', 'bubble-sort', 409),
  icon('bubble-sort-2', '相邻交换', '相邻元素比较交换', 'cs', 'bubble-sort', 410),
  icon('bubble-sort-3', '冒泡上浮', '相邻元素比较交换', 'cs', 'bubble-sort', 411),
  icon('binary-search-1', '二分查找', '区间折半逼近目标', 'cs', 'binary-search', 412),
  icon('binary-search-2', '折半搜索', '区间折半逼近目标', 'cs', 'binary-search', 413),
  icon('binary-search-3', '有序查找', '区间折半逼近目标', 'cs', 'binary-search', 414),
  icon('bfs-expand-1', '广度优先', '逐层扩展搜索前沿', 'cs', 'bfs-expand', 415),
  icon('bfs-expand-2', 'BFS 扩散', '逐层扩展搜索前沿', 'cs', 'bfs-expand', 416),
  icon('bfs-expand-3', '层序遍历', '逐层扩展搜索前沿', 'cs', 'bfs-expand', 417),
  icon('dfs-path-1', '深度优先', '沿路径深入再回溯', 'cs', 'dfs-path', 418),
  icon('dfs-path-2', 'DFS 回溯', '沿路径深入再回溯', 'cs', 'dfs-path', 419),
  icon('dfs-path-3', '栈式深入', '沿路径深入再回溯', 'cs', 'dfs-path', 420),
  icon('stack-push-1', '栈操作', '元素压入弹出栈顶', 'cs', 'stack-push', 421),
  icon('stack-push-2', '压栈弹栈', '元素压入弹出栈顶', 'cs', 'stack-push', 422),
  icon('stack-push-3', '后进先出', '元素压入弹出栈顶', 'cs', 'stack-push', 423),
  icon('queue-flow-1', '队列操作', '队尾入队队首出队', 'cs', 'queue-flow', 424),
  icon('queue-flow-2', '入队出队', '队尾入队队首出队', 'cs', 'queue-flow', 425),
  icon('queue-flow-3', '先进先出', '队尾入队队首出队', 'cs', 'queue-flow', 426),
  icon('hash-chain-1', '哈希表', '桶内链表处理冲突', 'cs', 'hash-chain', 427),
  icon('hash-chain-2', '链地址法', '桶内链表处理冲突', 'cs', 'hash-chain', 428),
  icon('hash-chain-3', '冲突消解', '桶内链表处理冲突', 'cs', 'hash-chain', 429),
  icon('recursion-tree-1', '递归树', '递归调用树形展开', 'cs', 'recursion-tree', 430),
  icon('recursion-tree-2', '分治递归', '递归调用树形展开', 'cs', 'recursion-tree', 431),
  icon('recursion-tree-3', '调用栈展开', '递归调用树形展开', 'cs', 'recursion-tree', 432),
  icon('heapify-1', '堆化', '节点下沉上浮维护堆', 'cs', 'heapify', 433),
  icon('heapify-2', '优先队列', '节点下沉上浮维护堆', 'cs', 'heapify', 434),
  icon('heapify-3', '堆调整', '节点下沉上浮维护堆', 'cs', 'heapify', 435),
  icon('graph-edge-1', '图遍历', '边权逐步松弛更新', 'cs', 'graph-edge', 436),
  icon('graph-edge-2', '边松弛', '边权逐步松弛更新', 'cs', 'graph-edge', 437),
  icon('graph-edge-3', '最短路径', '边权逐步松弛更新', 'cs', 'graph-edge', 438),
  icon('linked-list-1', '链表', '节点指针串联遍历', 'cs', 'linked-list', 439),
  icon('linked-list-2', '指针链接', '节点指针串联遍历', 'cs', 'linked-list', 440),
  icon('linked-list-3', '节点插入', '节点指针串联遍历', 'cs', 'linked-list', 441),
  icon('cache-line-1', '缓存命中', '命中与逐出交替', 'cs', 'cache-line', 442),
  icon('cache-line-2', 'LRU 替换', '命中与逐出交替', 'cs', 'cache-line', 443),
  icon('cache-line-3', '缓存行', '命中与逐出交替', 'cs', 'cache-line', 444),
  icon('neural-net-1', '神经网络', '层间信号前向流动', 'cs', 'neural-layers', 445),
  icon('neural-net-2', '前向传播', '层间信号前向流动', 'cs', 'neural-layers', 446),
  icon('neural-net-3', '反向梯度', '层间信号前向流动', 'cs', 'neural-layers', 447),
  icon('git-merge', 'Git 合并', '分支合并提交', 'cs', 'git-merge', 448),
  icon('prism-1', '棱镜色散', '不同波长折射角分离', 'optics', 'prism-dispers', 449),
  icon('prism-2', '白光色散', '不同波长折射角分离', 'optics', 'prism-dispers', 450),
  icon('prism-3', '折射分光', '不同波长折射角分离', 'optics', 'prism-dispers', 451),
  icon('grating-1', '光栅衍射', '光栅多缝干涉图样', 'optics', 'grating-diffract', 452),
  icon('grating-2', '衍射条纹', '光栅多缝干涉图样', 'optics', 'grating-diffract', 453),
  icon('grating-3', '夫琅禾费衍射', '光栅多缝干涉图样', 'optics', 'grating-diffract', 454),
  icon('lens-1', '凸透镜', '平行光汇聚于焦点', 'optics', 'lens-focus', 455),
  icon('lens-2', '透镜成像', '平行光汇聚于焦点', 'optics', 'lens-focus', 456),
  icon('lens-3', '焦点汇聚', '平行光汇聚于焦点', 'optics', 'lens-focus', 457),
  icon('mirror-1', '凹面镜', '反射光线汇聚', 'optics', 'mirror-reflect', 458),
  icon('mirror-2', '反射聚焦', '反射光线汇聚', 'optics', 'mirror-reflect', 459),
  icon('mirror-3', '镜面成像', '反射光线汇聚', 'optics', 'mirror-reflect', 460),
  icon('polar-1', '偏振光', '偏振方向选择性透过', 'optics', 'polarization', 461),
  icon('polar-2', '偏振片旋转', '偏振方向选择性透过', 'optics', 'polarization', 462),
  icon('polar-3', '马吕斯定律', '偏振方向选择性透过', 'optics', 'polarization', 463),
  icon('laser-1', '激光腔', '腔内光来回放大', 'optics', 'laser-cavity', 464),
  icon('laser-2', '受激辐射', '腔内光来回放大', 'optics', 'laser-cavity', 465),
  icon('laser-3', '激光振荡', '腔内光来回放大', 'optics', 'laser-cavity', 466),
  icon('fiber-1', '光纤传输', '纤芯全反射导光', 'optics', 'fiber-tir', 467),
  icon('fiber-2', '全反射导光', '纤芯全反射导光', 'optics', 'fiber-tir', 468),
  icon('fiber-3', '光导纤维', '纤芯全反射导光', 'optics', 'fiber-tir', 469),
  icon('interf-ring-1', '等倾干涉', '同心干涉环明暗', 'optics', 'interference-ring', 470),
  icon('interf-ring-2', '牛顿环', '同心干涉环明暗', 'optics', 'interference-ring', 471),
  icon('interf-ring-3', '薄膜干涉', '同心干涉环明暗', 'optics', 'interference-ring', 472),
  icon('thin-film-1', '增透膜', '膜厚控制反射相位', 'optics', 'thin-film', 473),
  icon('thin-film-2', '薄膜相位', '膜厚控制反射相位', 'optics', 'thin-film', 474),
  icon('thin-film-3', '多层膜', '膜厚控制反射相位', 'optics', 'thin-film', 475),
  icon('telescope', '望远镜', '物镜像面组成像', 'optics', 'telescope-focus', 476),
  icon('hologram', '全息重建', '参考光干涉重建', 'optics', 'interference-ring', 477),
  icon('michelson-mirror', '迈克尔逊', '分束干涉仪', 'optics', 'interference-ring', 478),
  icon('plate-1', '板块俯冲', '板块碰撞俯冲消减', 'earth', 'plate-subduct', 479),
  icon('plate-2', '俯冲带', '板块碰撞俯冲消减', 'earth', 'plate-subduct', 480),
  icon('plate-3', '大洋板块', '板块碰撞俯冲消减', 'earth', 'plate-subduct', 481),
  icon('volcano-1', '火山喷发', '岩浆喷出与碎屑', 'earth', 'volcano-erupt', 482),
  icon('volcano-2', '岩浆喷发', '岩浆喷出与碎屑', 'earth', 'volcano-erupt', 483),
  icon('volcano-3', '火山口', '岩浆喷出与碎屑', 'earth', 'volcano-erupt', 484),
  icon('seismic-1', '地震波', '体波与面波传播', 'earth', 'seismic-wave', 485),
  icon('seismic-2', 'P 波传播', '体波与面波传播', 'earth', 'seismic-wave', 486),
  icon('seismic-3', 'S 波横波', '体波与面波传播', 'earth', 'seismic-wave', 487),
  icon('front-1', '冷锋过境', '冷暖空气交界推进', 'earth', 'cold-front', 488),
  icon('front-2', '暖锋抬升', '冷暖空气交界推进', 'earth', 'cold-front', 489),
  icon('front-3', '锋面雨带', '冷暖空气交界推进', 'earth', 'cold-front', 490),
  icon('hurricane-1', '飓风眼', '低压气旋旋转结构', 'earth', 'hurricane-spin', 491),
  icon('hurricane-2', '气旋旋转', '低压气旋旋转结构', 'earth', 'hurricane-spin', 492),
  icon('hurricane-3', '台风涡旋', '低压气旋旋转结构', 'earth', 'hurricane-spin', 493),
  icon('ocean-1', '洋流环流', '海水大规模环流', 'earth', 'ocean-gyre', 494),
  icon('ocean-2', '赤道环流', '海水大规模环流', 'earth', 'ocean-gyre', 495),
  icon('ocean-3', '温盐环流', '海水大规模环流', 'earth', 'ocean-gyre', 496),
  icon('glacier-1', '冰川运动', '重力驱动冰体缓慢流动', 'earth', 'glacier-flow', 497),
  icon('glacier-2', '冰河推进', '重力驱动冰体缓慢流动', 'earth', 'glacier-flow', 498),
  icon('glacier-3', '冰舌延伸', '重力驱动冰体缓慢流动', 'earth', 'glacier-flow', 499),
  icon('season-1', '四季成因', '地轴倾角导致季节', 'earth', 'season-tilt', 500),
  icon('season-2', '地轴倾斜', '地轴倾角导致季节', 'earth', 'season-tilt', 501),
  icon('season-3', '日照变化', '地轴倾角导致季节', 'earth', 'season-tilt', 502),
  icon('fault-1', '断层滑动', '岩层沿断层面错动', 'earth', 'fault-slip', 503),
  icon('fault-2', '走滑断层', '岩层沿断层面错动', 'earth', 'fault-slip', 504),
  icon('fault-3', '地震断层', '岩层沿断层面错动', 'earth', 'fault-slip', 505),
  icon('groundwater', '地下水', '含水层渗透', 'earth', 'groundwater', 506),
  icon('watershed', '流域汇流', '降水地表汇流', 'earth', 'groundwater', 507),
  icon('metronome-1', '节拍器', '摆锤左右稳定节拍', 'music', 'metronome', 508),
  icon('metronome-2', '稳定节拍', '摆锤左右稳定节拍', 'music', 'metronome', 509),
  icon('metronome-3', '节奏器', '摆锤左右稳定节拍', 'music', 'metronome', 510),
  icon('string-harm-1', '弦乐泛音', '弦上驻波与泛音列', 'music', 'string-harmonic', 511),
  icon('string-harm-2', '驻波泛音', '弦上驻波与泛音列', 'music', 'string-harmonic', 512),
  icon('string-harm-3', '弦振动', '弦上驻波与泛音列', 'music', 'string-harmonic', 513),
  icon('drum-1', '鼓点节奏', '周期性敲击脉冲', 'music', 'drum-pulse', 514),
  icon('drum-2', '打击节拍', '周期性敲击脉冲', 'music', 'drum-pulse', 515),
  icon('drum-3', '底鼓脉冲', '周期性敲击脉冲', 'music', 'drum-pulse', 516),
  icon('tube-1', '管乐共振', '管中驻波共振模', 'music', 'tube-resonance', 517),
  icon('tube-2', '开管闭管', '管中驻波共振模', 'music', 'tube-resonance', 518),
  icon('tube-3', '气柱共振', '管中驻波共振模', 'music', 'tube-resonance', 519),
  icon('piano-1', '钢琴击弦', '琴锤击弦发声', 'music', 'piano-key', 520),
  icon('piano-2', '琴键击弦', '琴锤击弦发声', 'music', 'piano-key', 521),
  icon('piano-3', '锤击琴弦', '琴锤击弦发声', 'music', 'piano-key', 522),
  icon('spectrum-1', '频谱瀑布', '频率成分随时间分布', 'music', 'spectrum-fall', 523),
  icon('spectrum-2', '频谱分析', '频率成分随时间分布', 'music', 'spectrum-fall', 524),
  icon('spectrum-3', '音色频谱', '频率成分随时间分布', 'music', 'spectrum-fall', 525),
  icon('vibrato-1', '揉弦颤音', '音高周期性微扰', 'music', 'vibrato-pitch', 526),
  icon('vibrato-2', '音高颤动', '音高周期性微扰', 'music', 'vibrato-pitch', 527),
  icon('vibrato-3', '颤音效果', '音高周期性微扰', 'music', 'vibrato-pitch', 528),
  icon('beat-mix-1', '拍频合成', '相近频率合成拍频', 'music', 'beat-mix', 529),
  icon('beat-mix-2', '双音拍频', '相近频率合成拍频', 'music', 'beat-mix', 530),
  icon('beat-mix-3', '拍音', '相近频率合成拍频', 'music', 'beat-mix', 531),
  icon('conductor', '指挥棒', '指挥挥拍', 'music', 'conductor-wave', 532),
  icon('four-bar-1', '四连杆', '四杆闭环传动', 'engineering', 'four-bar-link', 533),
  icon('four-bar-2', '曲柄摇杆', '四杆闭环传动', 'engineering', 'four-bar-link', 534),
  icon('four-bar-3', '连杆机构', '四杆闭环传动', 'engineering', 'four-bar-link', 535),
  icon('cam-1', '凸轮机构', '凸轮推动从动件', 'engineering', 'cam-follower', 536),
  icon('cam-2', '凸轮从动', '凸轮推动从动件', 'engineering', 'cam-follower', 537),
  icon('cam-3', '轮廓传动', '凸轮推动从动件', 'engineering', 'cam-follower', 538),
  icon('piston-1', '活塞冲程', '活塞往复四冲程', 'engineering', 'piston-cycle', 539),
  icon('piston-2', '内燃冲程', '活塞往复四冲程', 'engineering', 'piston-cycle', 540),
  icon('piston-3', '往复运动', '活塞往复四冲程', 'engineering', 'piston-cycle', 541),
  icon('gear-1', '齿轮传动', '齿面啮合传递转速', 'engineering', 'gear-train', 542),
  icon('gear-2', '齿轮啮合', '齿面啮合传递转速', 'engineering', 'gear-train', 543),
  icon('gear-3', '齿比传动', '齿面啮合传递转速', 'engineering', 'gear-train', 544),
  icon('bridge-1', '桥梁振动', '结构弯曲振动模态', 'engineering', 'bridge-vibrate', 545),
  icon('bridge-2', '悬索振动', '结构弯曲振动模态', 'engineering', 'bridge-vibrate', 546),
  icon('bridge-3', '共振模态', '结构弯曲振动模态', 'engineering', 'bridge-vibrate', 547),
  icon('crane-1', '塔吊回转', '起重臂回转吊运', 'engineering', 'crane-jib', 548),
  icon('crane-2', '起重臂', '起重臂回转吊运', 'engineering', 'crane-jib', 549),
  icon('crane-3', '吊装回转', '起重臂回转吊运', 'engineering', 'crane-jib', 550),
  icon('conveyor-1', '传送带', '皮带连续输送物料', 'engineering', 'conveyor-belt', 551),
  icon('conveyor-2', '皮带输送', '皮带连续输送物料', 'engineering', 'conveyor-belt', 552),
  icon('conveyor-3', '物料输送', '皮带连续输送物料', 'engineering', 'conveyor-belt', 553),
  icon('turbine-1', '涡轮叶片', '流体推动叶轮旋转', 'engineering', 'turbine-spin', 554),
  icon('turbine-2', '叶轮旋转', '流体推动叶轮旋转', 'engineering', 'turbine-spin', 555),
  icon('turbine-3', '水轮机', '流体推动叶轮旋转', 'engineering', 'turbine-spin', 556),
  icon('lever-pulley', '杠杆滑轮', '滑轮组提升', 'engineering', 'lever-pulley', 557),
  icon('epsilon-delta', 'ε-δ 定义', '极限严格定义', 'calculus', 'ladder-limit', 558),
  icon('rolle-theorem', '罗尔定理', '区间内存在水平切线', 'calculus', 'derivative-slope', 559),
  icon('mean-value', '拉格朗日中值', '区间内存在平行切线', 'calculus', 'derivative-slope', 560),
  icon('improper-integral', '反常积分', '无穷区间积分收敛', 'calculus', 'integral-bounds', 561),
  icon('parametric-curve', '参数曲线', 'x(t),y(t) 参数运动', 'calculus', 'lissajous', 562),
  icon('unit-circle-trig', '单位圆三角', '三角函数单位圆定义', 'trigonometry', 'phasor-rotate', 563),
  icon('arcsin-wave', '反正弦', 'arcsin 定义域映射', 'trigonometry', 'sine-wave', 564),
  icon('arccos-wave', '反余弦', 'arccos 值域映射', 'trigonometry', 'cosine-wave', 565),
  icon('tan-asymptote', '正切渐近线', 'tan 奇点竖渐近', 'trigonometry', 'derivative-slope', 566),
  icon('cot-period', '余切周期', 'cot 周期振荡', 'trigonometry', 'sine-wave', 567),
  icon('sec-amplify', '正割放大', 'sec 振幅放大', 'trigonometry', 'cosine-wave', 568),
  icon('csc-inverse', '余割倒数', 'csc 与 sin 倒数', 'trigonometry', 'sine-wave', 569),
  icon('half-angle', '半角公式', 'sin(θ/2) 恒等变换', 'trigonometry', 'beat-frequency', 570),
  icon('sum-formula', '和差公式', 'sin(a±b) 展开', 'trigonometry', 'wave-interference', 571),
  icon('desargues', '德萨格定理', '透视三角形共线', 'geometry', 'matrix-pulse', 572),
  icon('penrose-tile', '彭罗斯镶嵌', '非周期镶嵌铺砌', 'geometry', 'voronoi-pulse', 573),
  icon('delone-tri', 'Delaunay 三角', '空圆三角剖分', 'geometry', 'voronoi-pulse', 574),
  icon('steiner-tree', '斯坦纳树', '最短连接网络', 'geometry', 'bifurcation-fork', 575),
  icon('fractal-tree', '分形树', '递归分支生长', 'geometry', 'bifurcation-fork', 576),
  icon('tessellation', '平面镶嵌', '对称群平铺', 'geometry', 'matrix-pulse', 577),
  icon('sn1-reaction', 'SN1 取代', '单分子亲核取代', 'chemistry', 'molecular-bond', 578),
  icon('sn2-reaction', 'SN2 取代', '双分子背面进攻', 'chemistry', 'molecular-bond', 579),
  icon('esterification', '酯化反应', '酸醇脱水成酯', 'chemistry', 'equilibrium-shift', 580),
  icon('hydrolysis', '水解反应', '键断裂加水', 'chemistry', 'redox-transfer', 581),
  icon('polymer-chain', '聚合反应', '单体链式增长', 'chemistry', 'molecular-bond', 582),
  icon('catalyst-surface', '催化表面', '吸附活化脱附', 'chemistry', 'reaction-diffusion', 583),
  icon('ph-indicator', 'pH 指示剂', '酸碱变色范围', 'chemistry', 'titration-endpoint', 584),
  icon('galvanic-cell', '原电池', '自发氧化还原电流', 'chemistry', 'redox-transfer', 585),
  icon('electrolysis-cell', '电解池', '外加电压驱动', 'chemistry', 'redox-transfer', 586),
  icon('chromatography', '色谱分离', '组分沿柱洗脱', 'chemistry', 'equilibrium-shift', 587),
  icon('mass-spec', '质谱扫描', 'm/z 峰扫描', 'chemistry', 'nmr-flip', 588),
  icon('ir-spectrum', '红外光谱', '键振动吸收峰', 'chemistry', 'fourier-bars', 589),
  icon('wormhole', '虫洞', '时空短程连接', 'relativity', 'gravitational-lens', 590),
  icon('cosmological-constant', '宇宙学常数', '加速膨胀驱动', 'relativity', 'hubble-expansion', 591),
  icon('gravitational-redshift', '引力红移', '光子爬出势阱变红', 'relativity', 'redshift-spectrum', 592),
  icon('shapiro-delay', '夏皮罗延迟', '光线引力场延迟', 'relativity', 'gravitational-lens', 593),
  icon('ergosphere', '能层', '克尔黑洞能层', 'relativity', 'accretion-disk', 594),
  icon('penrose-process', '彭罗斯过程', '能层能量提取', 'relativity', 'accretion-disk', 595),
  icon('alcubierre', '阿库别里驱动', '曲率驱动气泡', 'relativity', 'light-cone', 596),
  icon('blandford-znajek', 'BZ 过程', '黑洞磁场能量提取', 'relativity', 'pulsar-beam', 597),
  icon('naked-singularity', '裸奇点', '无视界奇点', 'relativity', 'dirac-impulse', 598),
  icon('ads-cft', 'AdS/CFT', '体边界对偶', 'relativity', 'light-cone', 599),
  icon('exoplanet-transit', '系外行星凌日', '亮度周期性下降', 'astronomy', 'logistic-curve', 600),
  icon('habitable-zone', '宜居带', '液态水轨道带', 'astronomy', 'orbit-ellipse', 601),
  icon('tidal-heating', '潮汐加热', '椭圆轨道摩擦生热', 'astronomy', 'tidal-bulge', 602),
  icon('ring-resonance', '环系共振', '牧羊卫星共振', 'astronomy', 'orbital-resonance', 603),
  icon('stellar-wind-bubble', '恒星风泡', '星风吹出泡状结构', 'astronomy', 'radial-particle-wind', 604),
  icon('planetary-migration', '行星迁移', '盘力轨道内移', 'astronomy', 'orbit-ellipse', 605),
  icon('dust-disk', '原行星盘', '尘埃盘螺旋结构', 'astronomy', 'spiral-golden', 606),
  icon('microlensing', '微引力透镜', '前景星放大背景', 'astronomy', 'gravitational-lens', 607),
  icon('fast-radio-burst', '快速射电暴', '毫秒射电爆发', 'astronomy', 'dirac-impulse', 608),
  icon('pulsar-glitch', '脉冲星跳变', '中子星转速突变', 'astronomy', 'pulsar-beam', 609),
  icon('top-quark', '顶夸克', '最重夸克衰变', 'quantum', 'exponential-decay', 610),
  icon('higgs-boson', '希格斯玻色子', '质量赋予机制', 'quantum', 'energy-levels', 611),
  icon('gluon-jet', '胶子喷注', 'QCD 强子化喷流', 'quantum', 'particle-cascade', 612),
  icon('muon-g2', 'μ 子 g-2', '反常磁矩进动', 'quantum', 'spin-precession', 613),
  icon('anyon-braid', '任意子编织', '拓扑量子统计', 'quantum', 'trefoil-knot', 614),
  icon('majorana-zero', '马约拉纳零模', '拓扑零能态', 'quantum', 'tunnel-barrier', 615),
  icon('quantum-dot', '量子点', '受限能级跃迁', 'quantum', 'energy-levels', 616),
  icon('superconduct-qubit', '超导量子比特', '约瑟夫森结振荡', 'quantum', 'rlc-oscillation', 617),
];
