import type { IconCategory, IconDefinition, TemplateName } from './types.ts';
import { EXPANSION_CATALOG } from './catalog-expansion.ts';

// preserved 26 + qian-xuesen 1 + generated batch 173 + chemistry 10 + extension 12 + sports 24 + expansion 130 = 376

function icon(
  id: string,
  title: string,
  description: string,
  category: IconCategory,
  template: TemplateName,
  options: Partial<Pick<IconDefinition, 'seed' | 'preserve' | 'customSvg'>> = {},
): IconDefinition {
  return { id, title, description, category, template, ...options };
}

const PRESERVED_IDS = new Set([
  'sine-wave',
  'lissajous',
  'integral-bounds',
  'sigma-sum',
  'pendulum',
  'fourier-bars',
  'derivative-dt',
  'golden-spiral',
  'euler-circle',
  'gaussian-bell',
  'taylor-series',
  'exponential-decay',
  'logistic-curve',
  'kepler-orbit',
  'cycloid',
  'wave-interference',
  'pythagorean',
  'harmonic-spring',
  'hyperbola',
  'fibonacci-spiral',
  'light-cone',
  'brownian-motion',
  'double-slit',
  'gradient-descent',
  'projectile-arc',
  'catenary',
]);

function batch(
  items: Array<[string, string, string, IconCategory, TemplateName]>,
  startSeed = 1,
): IconDefinition[] {
  return items.map(([id, title, description, category, template], index) =>
    icon(id, title, description, category, template, {
      seed: startSeed + index,
      preserve: PRESERVED_IDS.has(id),
    }),
  );
}

const preserved = batch([
  ['sine-wave', '正弦波', 'y = sin(x)，相位沿曲线传播', 'trigonometry', 'sine-wave'],
  ['lissajous', '利萨如曲线', 'x = sin(at), y = sin(bt) 参数轨道', 'geometry', 'lissajous'],
  ['integral-bounds', '定积分', '∫ₐᵇ f(x)dx 积分上下界脉动', 'calculus', 'integral-bounds'],
  ['sigma-sum', '求和 Σ', 'Σaₙ 逐项累加', 'series', 'sigma-sum'],
  ['pendulum', '单摆', '小角度简谐振动', 'mechanics', 'pendulum'],
  ['fourier-bars', '傅里叶级数', '谐波分量依次伸缩', 'series', 'fourier-bars'],
  ['derivative-dt', '时间导数', 'd/dt 变化率与切线', 'calculus', 'derivative-slope'],
  ['golden-spiral', '黄金螺旋', 'φ 对数螺旋展开', 'geometry', 'spiral-golden'],
  ['euler-circle', '欧拉公式', 'e^(iθ) 单位圆相位旋转', 'trigonometry', 'phasor-rotate'],
  ['gaussian-bell', '正态分布', '高斯概率密度钟形曲线', 'statistics', 'gaussian-bell'],
  ['taylor-series', '泰勒级数', '逐项逼近目标函数', 'series', 'taylor-series'],
  ['exponential-decay', '指数衰减', 'N = N₀e^(-λt) 衰变', 'physics', 'exponential-decay'],
  ['logistic-curve', 'Logistic 函数', 'σ(x)=1/(1+e^(-x)) 饱和增长', 'calculus', 'logistic-curve'],
  ['kepler-orbit', '开普勒轨道', '行星椭圆轨道运动', 'astronomy', 'orbit-ellipse'],
  ['cycloid', '摆线', '圆滚动边缘点轨迹', 'geometry', 'cycloid-roll'],
  ['wave-interference', '波的干涉', '两列波相长相消叠加', 'physics', 'wave-interference'],
  ['pythagorean', '勾股定理', 'a² + b² = c²', 'geometry', 'pythagorean-pulse'],
  ['harmonic-spring', '弹簧振子', '胡克定律 F = -kx', 'mechanics', 'spring-oscillator'],
  ['hyperbola', '双曲线', 'x²/a² - y²/b² = 1', 'geometry', 'hyperbola-branch'],
  ['fibonacci-spiral', '斐波那契螺旋', '斐波那契矩形内圆弧', 'geometry', 'spiral-fibonacci'],
  ['light-cone', '光锥', '狭义相对论因果光锥', 'relativity', 'light-cone'],
  ['brownian-motion', '布朗运动', '粒子随机游走', 'statistics', 'brownian-motion'],
  ['double-slit', '双缝干涉', '杨氏干涉条纹', 'quantum', 'double-slit'],
  ['gradient-descent', '梯度下降', '沿 -∇f 迭代求极小', 'calculus', 'gradient-descent'],
  ['projectile-arc', '抛体运动', '重力场抛物线轨迹', 'mechanics', 'projectile-arc'],
  ['catenary', '悬链线', 'y = a·cosh(x/a)', 'geometry', 'catenary-sag'],
]);

const generated: IconDefinition[] = [
  icon(
    'qian-xuesen-trajectory',
    '钱学森弹道',
    '助推-滑翔式水漂弹道，临近空间跳跃飞行',
    'aerospace',
    'skip-glide-trajectory',
    { seed: 7 },
  ),
  ...batch(
    (
      [
      ['cosine-phase', '余弦波', 'y = cos(x) 相位传播', 'trigonometry', 'cosine-wave'],
      ['tangent-slope', '正切斜率', 'tan(x) 斜率突变示意', 'trigonometry', 'derivative-slope'],
      ['rose-petals', '玫瑰线', 'r = cos(kθ) 花瓣轨道', 'geometry', 'rose-curve'],
      ['cardioid-path', '心形线', 'r = 1 + cosθ 闭曲线', 'geometry', 'cardioid-loop'],
      ['lemniscate-eight', '双纽线', '∞ 形伯努利双纽线', 'geometry', 'lemniscate'],
      ['astroid-orbit', '星形线', 'x^(2/3) + y^(2/3) = a^(2/3)', 'geometry', 'astroid-roll'],
      ['epicycloid-gear', '外摆线', '大圆上小圆滚动轨迹', 'geometry', 'epicycloid'],
      ['brachistochrone-fast', '最速降线', '重力场最快下降路径', 'mechanics', 'brachistochrone'],
      ['isochrone-swing', '等时线', '等时降落曲线', 'mechanics', 'isochrone-curve'],
      ['parabola-focus', '抛物线', 'y = ax² 焦点反射', 'geometry', 'parabola-bowl'],
      ['mobius-strip', '莫比乌斯带', '单侧曲面沿带运动', 'geometry', 'mobius-travel'],
      ['torus-knot', '环面轨道', '环面参数闭轨道', 'geometry', 'torus-orbit'],
      ['voronoi-cell', '沃罗诺伊图', '最近邻区域划分', 'geometry', 'voronoi-pulse'],
      ['pythagorean-tree', '勾股树', '递归直角三角形生长', 'geometry', 'bifurcation-fork'],
      ['koch-flake', '科赫雪花', '分形边界迭代', 'chaos', 'koch-snowflake'],
      ['mandelbrot-orbit', '曼德博轨道', 'zₙ₊₁ = zₙ² + c 迭代', 'chaos', 'mandelbrot-orbit'],
      ['bifurcation-logistic', '倍周期分叉', 'Logistic 映射分叉', 'chaos', 'bifurcation-fork'],
      ['lorenz-attractor', '洛伦兹吸引子', '混沌系统轨道示意', 'chaos', 'brownian-motion'],
      ['dirac-delta', '狄拉克 δ', '脉冲集中分布', 'calculus', 'dirac-impulse'],
      ['laplace-transform', '拉普拉斯变换', '时域到 s 域衰减', 'calculus', 'laplace-decay'],
      ['stokes-theorem', '斯托克斯定理', '环流与旋度关系', 'calculus', 'stokes-circulation'],
      ['action-principle', '最小作用量', 'δS = 0 真实路径', 'mechanics', 'action-integral'],
      ['eigen-resonance', '本征共振', '本征模态振动', 'series', 'eigen-resonance'],
      ['matrix-rotation', '矩阵变换', '线性变换网格脉动', 'geometry', 'matrix-pulse'],
      ['regression-fit', '线性回归', '最小二乘拟合直线', 'statistics', 'regression-line'],
      ['monte-carlo', '蒙特卡洛', '随机采样估计', 'statistics', 'monte-carlo'],
      ['markov-chain', '马尔可夫链', '状态转移概率', 'statistics', 'markov-chain'],
      ['central-limit', '中心极限', '样本均值趋正态', 'statistics', 'gaussian-bell'],
      ['bayes-update', '贝叶斯更新', '后验概率迭代', 'statistics', 'logistic-curve'],
      ['standing-wave', '驻波', '节点与腹点振动', 'physics', 'standing-wave'],
      ['beat-frequency', '拍频', '相近频率合成拍', 'physics', 'beat-frequency'],
      ['doppler-effect', '多普勒效应', '相对运动频移', 'physics', 'doppler-shift'],
      ['wave-packet', '波包', '群速度与相速度', 'quantum', 'wave-packet'],
      ['schrodinger-cat', '薛定谔波包', 'ψ 概率幅传播', 'quantum', 'schrodinger-packet'],
      ['tunnel-effect', '量子隧穿', '势垒穿透概率', 'quantum', 'tunnel-barrier'],
      ['spin-precession', '自旋进动', '磁矩拉莫尔进动', 'quantum', 'spin-precession'],
      ['energy-quantum', '能级量子化', 'Eₙ 分立能级跃迁', 'quantum', 'energy-levels'],
      ['pauli-exclusion', '泡利不相容', '费米子能级填充', 'quantum', 'energy-levels'],
      ['maxwell-wave', '麦克斯韦波', '电场磁场交替传播', 'electromagnetism', 'maxwell-rotate'],
      ['faraday-induction', '法拉第感应', '磁通变化感生电动势', 'electromagnetism', 'faraday-loop'],
      ['rlc-circuit', 'RLC 振荡', 'LC 谐振电路', 'electromagnetism', 'rlc-oscillation'],
      ['coulomb-field', '库仑场', '点电荷径向场线', 'electromagnetism', 'field-divergence'],
      ['ampere-circulation', '安培环路', '电流产生环形磁场', 'electromagnetism', 'field-curl'],
      ['magnetic-reconnection', '磁重联', '磁力线断裂重接', 'electromagnetism', 'magnetic-reconnection'],
      ['bernoulli-pipe', '伯努利管', '流速增压力降', 'fluid', 'bernoulli-flow'],
      ['navier-vortex', '涡旋', '环量守恒涡旋', 'fluid', 'vortex-flow'],
      ['shock-wave', '激波', '超声速压缩波前', 'fluid', 'shock-compression'],
      ['heat-diffusion', '热扩散', '傅里叶热传导', 'thermodynamics', 'heat-diffusion'],
      ['carnot-engine', '卡诺循环', '可逆热机循环', 'thermodynamics', 'carnot-cycle'],
      ['entropy-growth', '熵增', '孤立系统无序度上升', 'thermodynamics', 'entropy-spread'],
      ['ideal-gas', '理想气体', 'PV = nRT 等温过程', 'thermodynamics', 'bernoulli-flow'],
      ['rocket-equation', '火箭方程', 'Δv = ve·ln(m₀/m₁)', 'aerospace', 'rocket-thrust'],
      ['hohmann-transfer', '霍曼转移', '最小能量轨道转移', 'aerospace', 'hohmann-transfer'],
      ['reentry-arc', '再入弹道', '大气层再入抛物线', 'aerospace', 'projectile-arc'],
      ['satellite-dish', '卫星姿态', '三轴稳定进动', 'aerospace', 'precession-wobble'],
      ['orbital-decay', '轨道衰减', '大气阻力降轨', 'aerospace', 'exponential-decay'],
      ['solar-sail', '太阳帆', '辐射压推进', 'aerospace', 'light-cone'],
      ['gravity-assist', '引力助推', '行星借力加速', 'aerospace', 'gravitational-lens'],
      ['iss-orbit', '空间站轨道', '近地圆轨道周期运动', 'aerospace', 'orbit-circle'],
      ['mars-transfer', '火星转移', '霍曼式地火转移', 'aerospace', 'hohmann-transfer'],
      ['moon-orbit', '月球轨道', '开普勒椭圆公转', 'astronomy', 'orbit-ellipse'],
      ['mercury-precession', '水星进动', '近日点相对论进动', 'astronomy', 'mercury-precession'],
      ['lagrange-l1', '拉格朗日点', 'L1 点受力强平衡', 'astronomy', 'lagrange-point'],
      ['roche-breakup', '洛希极限', '潮汐力撕裂天体', 'astronomy', 'roche-limit'],
      ['tidal-locking', '潮汐锁定', '自转与公转同步', 'astronomy', 'tidal-bulge'],
      ['planetary-ring', '行星环', '土星环粒子轨道', 'astronomy', 'planetary-ring'],
      ['comet-tail', '彗星尾', '太阳风吹拂离子尾', 'astronomy', 'comet-tail'],
      ['asteroid-belt', '小行星带', '轨道带粒子分布', 'astronomy', 'hubble-expansion'],
      ['accretion-disk', '吸积盘', '黑洞吸积盘旋转', 'astronomy', 'accretion-disk'],
      ['pulsar-beam', '脉冲星束', '磁极扫射脉冲', 'astronomy', 'pulsar-beam'],
      ['neutron-star', '中子星', '超高密度星体脉动', 'astronomy', 'neutron-star'],
      ['supernova-shock', '超新星激波', '壳层膨胀冲击波', 'astronomy', 'supernova-shell'],
      ['solar-flare', '太阳耀斑', '磁能爆发喷流', 'astronomy', 'solar-flare'],
      ['aurora-borealis', '极光', '磁层粒子激发发光', 'astronomy', 'aurora-curtain'],
      ['gravitational-lens', '引力透镜', '光线弯曲成像', 'relativity', 'gravitational-lens'],
      ['gravitational-wave', '引力波', '时空涟漪传播', 'relativity', 'gravitational-wave'],
      ['hubble-flow', '哈勃膨胀', '宇宙均匀膨胀', 'astronomy', 'hubble-expansion'],
      ['redshift-galaxy', '宇宙红移', '光谱线向长波移动', 'astronomy', 'redshift-spectrum'],
      ['black-hole-shadow', '黑洞阴影', '事件视界光晕', 'relativity', 'accretion-disk'],
      ['time-dilation', '时间膨胀', '强场下时钟变慢', 'relativity', 'light-cone'],
      ['spacetime-curve', '时空弯曲', '质量弯曲测地线', 'relativity', 'gravitational-lens'],
      ['precession-gyro', '陀螺进动', '角动量方向漂移', 'mechanics', 'precession-wobble'],
      ['coupled-oscillator', '耦合振子', '能量在两振子间交换', 'mechanics', 'spring-oscillator'],
      ['rolling-ball', '滚动小球', '纯滚动动能守恒', 'mechanics', 'cycloid-roll'],
      ['collision-elastic', '弹性碰撞', '动量动能守恒', 'mechanics', 'projectile-arc'],
      ['coriolis-deflect', '科里奥利偏转', '旋转系惯性力', 'mechanics', 'field-curl'],
      ['kepler-area', '面积定律', '半径矢量扫过等面积', 'astronomy', 'orbit-ellipse'],
      ['three-body', '三体问题', '多体引力混沌轨道', 'mechanics', 'lissajous'],
      ['virial-theorem', '维里定理', '势能与动能关系', 'mechanics', 'energy-levels'],
      ['hamilton-flow', '哈密顿流', '相空间保守流', 'mechanics', 'stokes-circulation'],
      ['poisson-bracket', '泊松括号', '正则方程演化', 'mechanics', 'field-curl'],
      ['noether-symmetry', '诺特对称', '连续对称对应守恒量', 'mechanics', 'action-integral'],
      ['fourier-transform', '傅里叶变换', '时频域互转', 'series', 'fourier-bars'],
      ['laplace-operator', '拉普拉斯算子', '∇² 势场扩散', 'calculus', 'heat-diffusion'],
      ['gradient-field', '梯度场', '∇f 最陡上升方向', 'calculus', 'field-divergence'],
      ['curl-field', '旋度场', '∇×F 环流密度', 'calculus', 'field-curl'],
      ['divergence-field', '散度场', '∇·F 源汇强度', 'calculus', 'field-divergence'],
      ['green-theorem', '格林公式', '区域积分与边界环流', 'calculus', 'stokes-circulation'],
      ['line-integral', '线积分', '沿曲线累积效应', 'calculus', 'action-integral'],
      ['surface-integral', '面积分', '曲面积分通量', 'calculus', 'stokes-circulation'],
      ['volume-integral', '体积分', '三维区域积分', 'calculus', 'heat-diffusion'],
      ['limit-process', '极限过程', 'ε-δ 趋近过程', 'calculus', 'logistic-curve'],
      ['continuity-wave', '连续性', '无断裂函数传播', 'calculus', 'sine-wave'],
      ['series-converge', '级数收敛', '部分和趋近极限', 'series', 'taylor-series'],
      ['power-series', '幂级数', 'Σaₙxⁿ 收敛半径', 'series', 'taylor-series'],
      ['zeta-harmonic', '调和级数', 'Σ1/n 发散示意', 'series', 'sigma-sum'],
      ['fourier-sawtooth', '锯齿波', '傅里叶合成锯齿', 'series', 'fourier-bars'],
      ['wavelet-local', '小波', '时频局部化分析', 'series', 'wave-packet'],
      ['hilbert-phase', '希尔伯特相', '解析信号相位', 'series', 'phasor-rotate'],
      ['nyquist-sampling', '奈奎斯特采样', '采样率与混叠', 'series', 'beat-frequency'],
      ['poisson-process', '泊松过程', '稀有事件到达', 'statistics', 'markov-chain'],
      ['random-walk-2d', '二维随机游走', '平面布朗路径', 'statistics', 'brownian-motion'],
      ['chi-square', '卡方分布', '拟合优度检验', 'statistics', 'gaussian-bell'],
      ['t-distribution', 't 分布', '小样本统计推断', 'statistics', 'gaussian-bell'],
      ['confidence-band', '置信带', '区间估计覆盖', 'statistics', 'regression-line'],
      ['hypothesis-test', '假设检验', '显著性阈值判定', 'statistics', 'dirac-impulse'],
      ['sinh-cosh', '双曲函数', 'sinh/cosh 指数组合', 'trigonometry', 'catenary-sag'],
      ['inverse-square', '平方反比', 'F ∝ 1/r² 场衰减', 'physics', 'field-divergence'],
      ['coulomb-oscillator', '库仑势', '1/r 势场轨道', 'physics', 'orbit-ellipse'],
      ['harmonic-quantum', '量子谐振子', '能级等间距跃迁', 'quantum', 'energy-levels'],
      ['zeeman-split', '塞曼分裂', '磁场能级劈裂', 'quantum', 'redshift-spectrum'],
      ['stark-effect', '斯塔克效应', '电场能级移动', 'quantum', 'energy-levels'],
      ['compton-scatter', '康普顿散射', '光子电子能量交换', 'quantum', 'doppler-shift'],
      ['photoelectric', '光电效应', '光子激发电子', 'quantum', 'dirac-impulse'],
      ['bohr-orbit', '玻尔轨道', '量子化角动量轨道', 'quantum', 'orbit-circle'],
      ['de-broglie', '德布罗意波', '物质波 λ = h/p', 'quantum', 'wave-packet'],
      ['heisenberg-uncertainty', '不确定性', 'Δx·Δp ≥ ℏ/2', 'quantum', 'wave-packet'],
      ['bell-inequality', '贝尔不等式', '纠缠关联违背', 'quantum', 'wave-interference'],
      ['quantum-entangle', '量子纠缠', '非定域关联对', 'quantum', 'wave-interference'],
      ['bose-einstein', '玻色凝聚', '宏观量子相干', 'quantum', 'gaussian-bell'],
      ['fermi-surface', '费米面', '金属电子占据边界', 'quantum', 'energy-levels'],
      ['plasma-oscillation', '等离子体振荡', '集体电荷振荡', 'physics', 'rlc-oscillation'],
      ['langmuir-wave', '朗缪尔波', '等离子体静电波', 'physics', 'standing-wave'],
      ['magnetopause', '磁层顶', '太阳风与磁层边界', 'physics', 'shock-compression'],
      ['solar-wind', '太阳风', '带电粒子流', 'astronomy', 'doppler-shift'],
      ['cosmic-ray', '宇宙线', '高能粒子轰击', 'astronomy', 'brownian-motion'],
      ['cmb-ripple', '微波背景', 'CMB 温度涨落', 'astronomy', 'gravitational-wave'],
      ['dark-matter-halo', '暗物质晕', '星系外围质量分布', 'astronomy', 'gaussian-bell'],
      ['dark-energy-exp', '暗能量', '加速膨胀驱动', 'astronomy', 'hubble-expansion'],
      ['binary-pulsar', '双脉冲星', '引力辐射能量损失', 'astronomy', 'pulsar-beam'],
      ['eclipse-transit', '凌日测光', '行星遮挡亮度下降', 'astronomy', 'logistic-curve'],
      ['radial-velocity', '视向速度', '光谱多普勒测速', 'astronomy', 'redshift-spectrum'],
      ['n-body-chaos', 'N 体混沌', '多体引力不可积', 'chaos', 'lissajous'],
      ['feigenbaum-route', '费根鲍姆路径', '通向混沌道路', 'chaos', 'bifurcation-fork'],
      ['julia-set', '朱利亚集', '复迭代边界分形', 'chaos', 'mandelbrot-orbit'],
      ['cantor-dust', '康托尔集', '中间三分之一移除', 'chaos', 'entropy-spread'],
      ['sierpinski-tri', '谢尔宾斯基', '三角分形镂空', 'chaos', 'koch-snowflake'],
      ['strange-attractor', '奇怪吸引子', '非周期轨道聚集', 'chaos', 'brownian-motion'],
      ['phase-portrait', '相图', '动力系统轨迹场', 'chaos', 'field-curl'],
      ['poincare-section', '庞加莱截面', '周期轨道截面点', 'chaos', 'orbit-circle'],
      ['van-der-pol', '范德波尔', '自激振荡系统', 'chaos', 'rlc-oscillation'],
      ['duffing-oscillator', '杜芬振子', '非线性刚度振荡', 'chaos', 'spring-oscillator'],
      ['navier-stokes-t', 'NS 方程', '粘性不可压流体', 'fluid', 'vortex-flow'],
      ['reynolds-number', '雷诺数', '层流湍流转变', 'fluid', 'bernoulli-flow'],
      ['boundary-layer', '边界层', '壁面速度梯度', 'fluid', 'bernoulli-flow'],
      ['cavitation-bubble', '空化泡', '低压汽泡溃灭', 'fluid', 'heat-diffusion'],
      ['tsunami-wave', '海啸波', '浅水长波传播', 'fluid', 'wave-interference'],
      ['kelvin-wave', '开尔文波', '旋转系重力波', 'fluid', 'standing-wave'],
      ['mhd-flux', '磁流体', '导电流体与磁场耦合', 'fluid', 'magnetic-reconnection'],
      ['stefan-boltzmann', '斯特藩定律', '热辐射功率 T⁴', 'thermodynamics', 'heat-diffusion'],
      ['blackbody-spectrum', '黑体谱', '普朗克辐射分布', 'thermodynamics', 'redshift-spectrum'],
      ['clausius-inequality', '克劳修斯不等式', '循环过程熵判据', 'thermodynamics', 'carnot-cycle'],
      ['maxwell-demon', '麦克斯韦妖', '信息降熵思想实验', 'thermodynamics', 'entropy-spread'],
      ['phase-transition', '相变', '临界点序参量突变', 'thermodynamics', 'bifurcation-fork'],
      ['ising-model', '伊辛模型', '自旋格点相变', 'thermodynamics', 'matrix-pulse'],
      ['landau-level', '朗道能级', '磁场量子化能级', 'quantum', 'energy-levels'],
      ['hall-conductance', '霍尔电导', '拓扑量子化平台', 'quantum', 'stokes-circulation'],
      ['josephson-junction', '约瑟夫森结', '超导相位隧穿', 'quantum', 'tunnel-barrier'],
      ['meissner-effect', '迈斯纳效应', '磁场从超导体排出', 'electromagnetism', 'field-divergence'],
      ['eddy-current', '涡电流', '导体中感应涡旋', 'electromagnetism', 'vortex-flow'],
      ['skin-effect', '趋肤效应', '交流电流表面集中', 'electromagnetism', 'exponential-decay'],
      ['waveguide-mode', '波导模', '驻波导模场型', 'electromagnetism', 'standing-wave'],
      ['antenna-dipole', '偶极天线', '振荡偶极辐射', 'electromagnetism', 'doppler-shift'],
      ['snells-law', '斯涅尔定律', '折射角正弦比', 'physics', 'projectile-arc'],
      ['total-reflection', '全反射', '临界角内全反射', 'physics', 'skip-glide-trajectory'],
      ['fabry-perot', '法布里-珀罗', '多光束干涉腔', 'physics', 'double-slit'],
      ['michelson-interfer', '迈克耳孙干涉', '等倾干涉条纹', 'physics', 'wave-interference'],
      ['raman-scatter', '拉曼散射', '频移非弹性散射', 'physics', 'redshift-spectrum'],
      ['moseley-law', '莫塞莱定律', '特征 X 射线频率', 'physics', 'redshift-spectrum'],
      ['raleigh-scatter', '瑞利散射', '短波散射主导', 'physics', 'doppler-shift'],
      ['chaos-pendulum', '混沌摆', '双摆敏感依赖初值', 'chaos', 'pendulum'],
      ['alpha-decay', 'α 衰变', '隧穿势垒放出 α 粒子', 'physics', 'tunnel-barrier'],
      ['beta-decay', 'β 衰变', '弱相互作用转化', 'physics', 'exponential-decay'],
      ['gamma-emit', 'γ 辐射', '核能级退激光子', 'physics', 'dirac-impulse'],
      ['fission-chain', '链式裂变', '中子引发持续裂变', 'physics', 'bifurcation-fork'],
      ['fusion-plasma', '核聚变', '托卡马克约束等离子体', 'physics', 'accretion-disk'],
      ['hawking-radiation', '霍金辐射', '黑洞热辐射蒸发', 'relativity', 'exponential-decay'],
      ['penrose-diagram', '彭罗斯图', '时空因果结构', 'relativity', 'light-cone'],
      ['geodesic-fall', '测地线下落', '自由落体沿测地线', 'relativity', 'projectile-arc'],
      ['twin-paradox', '双生子佯谬', '相对运动时间差', 'relativity', 'light-cone'],
      ['lorentz-boost', '洛伦兹 boost', '参考系速度变换', 'relativity', 'doppler-shift'],
      ['minkowski-metric', '闵氏度规', '时空间隔不变量', 'relativity', 'light-cone'],
      ['schwarzschild-r', '施瓦西半径', '事件视界半径尺度', 'relativity', 'accretion-disk'],
      ['kerr-spin', '克尔自旋', '旋转黑洞拖拽', 'relativity', 'accretion-disk'],
      ['frame-dragging', '参考系拖拽', '能流拖曳时空', 'relativity', 'vortex-flow'],
      ['gps-relativity', 'GPS 相对论', '卫星钟速修正', 'relativity', 'orbit-circle'],
      ['lunar-phases', '月相周期', '日月地相对位置', 'astronomy', 'orbit-ellipse'],
      ['eclipse-umbra', '日食本影', '月球本影扫过', 'astronomy', 'logistic-curve'],
      ['milky-way-arm', '银河旋臂', '星系旋臂恒星形成', 'astronomy', 'spiral-golden'],
      ['quasar-jet', '类星体喷流', '活动星系核喷流', 'astronomy', 'solar-flare'],
      ['gamma-burst', '伽马暴', '短时高能爆发', 'astronomy', 'dirac-impulse'],
      ['magnetar-flare', '磁星爆发', '极强磁场星耀斑', 'astronomy', 'solar-flare'],
      ['oort-cloud', '奥尔特云', '长周期彗星源区', 'astronomy', 'hubble-expansion'],
      ['kuiper-belt', '柯伊伯带', '海王星外小天带', 'astronomy', 'planetary-ring'],
      ['n-body-sim', 'N 体模拟', '数值引力积分', 'astronomy', 'orbit-ellipse'],
      ['stellar-evolution', '恒星演化', '主序到红巨星', 'astronomy', 'logistic-curve'],
      ['hr-diagram', '赫罗图', '光度温度分布', 'astronomy', 'regression-line'],
      ['cepheid-pulse', '造父变星', '周光关系脉动', 'astronomy', 'sine-wave'],
      ['type-ia-supernova', 'Ia 型超新星', '标准烛光爆发', 'astronomy', 'supernova-shell'],
      ['neutrino-oscill', '中微子振荡', '味本征态混合', 'quantum', 'wave-interference'],
      ['ckm-matrix', 'CKM 矩阵', '夸克混合幺正变换', 'quantum', 'matrix-pulse'],
      ['yang-mills', '杨-米尔斯场', '非阿贝尔规范场', 'physics', 'field-curl'],
      ['higgs-mechanism', '希格斯机制', '对称性自发破缺', 'physics', 'energy-levels'],
      ['standard-model', '标准模型', '粒子物理统一框架', 'physics', 'bifurcation-fork'],
      ['feynman-path', '费曼路径', '量子历史求和', 'quantum', 'action-integral'],
      ['casimir-effect', '卡西米尔效应', '真空涨落力', 'quantum', 'wave-interference'],
      ['hawking-unruh', '安鲁效应', '加速观察者热浴', 'relativity', 'heat-diffusion'],
    ] as Array<[string, string, string, IconCategory, TemplateName]>
    ).slice(0, 173),
    100,
  ),
  ...batch(
    [
      ['atom-shells', '原子壳层', 'K/L/M 电子壳层轨道', 'chemistry', 'atom-shells'],
      ['molecular-bond', '共价键', '原子间共享电子对成键', 'chemistry', 'molecular-bond'],
      ['benzene-ring', '苯环', '芳香性 π 电子离域', 'chemistry', 'benzene-ring'],
      ['crystal-lattice', '晶体晶格', '空间点阵周期性结构', 'chemistry', 'crystal-lattice'],
      ['p-orbital', 'p 轨道', '哑铃形电子云概率分布', 'chemistry', 'p-orbital'],
      ['ionic-lattice', '离子晶体', '阴阳离子静电吸引晶格', 'chemistry', 'ionic-lattice'],
      ['sp3-hybrid', 'sp³ 杂化', '四面体杂化轨道成键', 'chemistry', 'sp3-hybrid'],
      ['periodic-cell', '周期表元胞', '元素周期表单格信息', 'chemistry', 'periodic-cell'],
      ['lewis-dots', '路易斯结构', '价电子点式表示', 'chemistry', 'lewis-dots'],
      ['equilibrium-shift', '化学平衡', '勒夏特列原理双向移动', 'chemistry', 'equilibrium-shift'],
    ],
    300,
  ),
  ...batch(
    [
      ['archimedes-spiral', '阿基米德螺线', 'r = aθ 等距螺旋展开', 'geometry', 'archimedes-spiral'],
      ['trefoil-knot', '三叶结', '非平凡纽结闭路追踪', 'geometry', 'trefoil-knot'],
      ['riemann-rectangles', '黎曼和', '矩形条带逐块逼近积分', 'calculus', 'riemann-rectangles'],
      ['wheel-paradox', '轮子悖论', '同心轮同步滚动标记', 'mechanics', 'wheel-paradox'],
      ['ladder-limit', '夹逼极限', '上下界阶梯夹逼收敛', 'calculus', 'ladder-limit'],
      ['monte-carlo-hit', '蒙特卡洛 π', '随机投点圆内命中计数', 'statistics', 'monte-carlo-hit'],
      ['redox-transfer', '氧化还原', '电子在物种间跃迁转移', 'chemistry', 'redox-transfer'],
      ['titration-endpoint', '滴定终点', '等当点附近 pH 陡升', 'chemistry', 'titration-endpoint'],
      ['nmr-flip', 'NMR 自旋翻转', '核磁自旋能级跃迁', 'chemistry', 'nmr-flip'],
      ['reaction-diffusion', '反应扩散', '图灵斑图生成与消长', 'chemistry', 'reaction-diffusion'],
      ['magnet-flip', '磁偶极翻转', '磁矩方向周期性反转', 'electromagnetism', 'magnet-flip'],
      ['orbital-resonance', '轨道共振', '2:1 周期锁定对齐', 'astronomy', 'orbital-resonance'],
    ],
    320,
  ),
  ...batch(
    [
      ['sprint-dash', '短跑冲刺', '摆臂蹬腿交替加速', 'sports', 'sprint-runner'],
      ['basketball-bounce', '篮球运球', '抛物线反弹节奏', 'sports', 'basketball-bounce'],
      ['soccer-dribble', '足球盘带', '脚背触球推进', 'sports', 'soccer-dribble'],
      ['swim-freestyle', '自由泳', '划水换气循环', 'sports', 'swim-crawl'],
      ['cycle-sprint', '公路骑行', '双轮转动踏频', 'sports', 'cycle-road'],
      ['tennis-volley', '网球截击', '球拍击球过网', 'sports', 'tennis-rally'],
      ['ski-slalom', '滑雪回转', '旗门间 S 形滑降', 'sports', 'ski-slalom'],
      ['jump-rope', '跳绳', '绳弧跳跃节奏', 'sports', 'jump-rope'],
      ['yoga-tree-pose', '瑜伽树式', '单腿平衡微摆', 'sports', 'yoga-tree'],
      ['boxing-jab', '拳击刺拳', '直拳出拳回收', 'sports', 'boxing-jab'],
      ['archery-release', '射箭发射', '拉弓释箭飞行', 'sports', 'archery-aim'],
      ['high-jump', '背越式跳高', '过杆抛物弧线', 'sports', 'high-jump-bar'],
      ['hurdle-race', '跨栏冲刺', '助跑起跳越栏落地', 'sports', 'hurdle-sprint'],
      ['pole-vault', '撑竿跳', '持竿插地过杆下坠', 'sports', 'pole-vault'],
      ['javelin-throw', '标枪投掷', '助跑引臂掷枪飞行', 'sports', 'javelin-throw'],
      ['shot-put', '铅球投掷', '旋转推掷铅球抛物', 'sports', 'shot-put'],
      ['hammer-throw', '链球投掷', '旋转甩链球离手', 'sports', 'hammer-throw'],
      ['triple-jump', '三级跳远', '单脚跳跨步跳远', 'sports', 'triple-jump'],
      ['weightlift', '举重挺举', '深蹲起杠过头', 'sports', 'weightlift'],
      ['volleyball-spike', '排球扣球', '助跑起跳扣球过网', 'sports', 'volleyball-spike'],
      ['dive-springboard', '跳板跳水', '起跳翻腾入水', 'sports', 'dive-board'],
      ['fencing-lunge', '击剑弓步', '弓步突刺回收', 'sports', 'fence-lunge'],
      ['skateboard-ollie', '滑板腾跃', '踩板起跳落地', 'sports', 'skate-ollie'],
      ['rowing-stroke', '赛艇划桨', '抓水拉桨回桨', 'sports', 'row-stroke'],
    ],
    340,
  ),
];

const CATALOG_FIXES: Partial<
  Record<string, Pick<IconDefinition, 'template' | 'title' | 'description' | 'category'>>
> = {
  'lorenz-attractor': { template: 'lorenz-butterfly' },
  'strange-attractor': { template: 'lorenz-butterfly', description: '奇怪吸引子上的非周期轨道' },
  'cosmic-ray': { template: 'particle-cascade', description: '高能粒子在大气中级联簇射' },
  'ideal-gas': { template: 'ideal-gas-isotherm', description: 'PV = nRT 等温双曲线过程' },
  'solar-sail': { template: 'radiation-sail', description: '太阳光压推动帆板加速' },
  'gravity-assist': { template: 'flyby-gravity-assist', description: '行星引力弹弓双曲线飞越' },
  'asteroid-belt': { template: 'asteroid-belt', description: '火星木星间轨道带小行星群' },
  'collision-elastic': { template: 'elastic-collision', description: '两体弹性碰撞动量交换' },
  'snells-law': { template: 'snell-refraction', description: 'n₁sinθ₁ = n₂sinθ₂ 折射定律' },
  'total-reflection': { template: 'total-internal-reflection', description: '临界角以上全内反射' },
  'fusion-plasma': { template: 'tokamak-fusion', description: '托卡马克磁约束等离子体环' },
  'cantor-dust': { template: 'cantor-prune', description: '反复删去中间三分之一区间' },
  'fermi-surface': { template: 'fermi-contour', description: '零温电子占据的费米等高面' },
  'virial-theorem': { template: 'virial-exchange', description: '⟨T⟩ 与 ⟨V⟩ 时间平均交换' },
  'hall-conductance': { template: 'hall-plateau', description: '霍尔电导量子化平台' },
  'antenna-dipole': { template: 'dipole-antenna', description: '偶极子振荡向外辐射电磁波' },
  'raleigh-scatter': { template: 'rayleigh-scatter', description: 'λ⁻⁴ 短波瑞利散射' },
  'solar-wind': { template: 'radial-particle-wind', description: '太阳风带电粒子径向流出' },
  'cmb-ripple': { template: 'cmb-ripple', description: '宇宙微波背景温度涨落波纹' },
  'oort-cloud': { template: 'oort-cloud-shell', description: '太阳系外围球壳彗星云' },
  'volume-integral': { template: 'volume-fill', description: '体域 Ω 上 ∫∫∫ f dV 填充累积' },
  'poisson-bracket': { template: 'phase-space-flow', description: '相空间泊松括号流演化' },
  'schrodinger-cat': {
    title: '薛定谔波包',
    description: 'ψ(x,t) 概率幅波包传播',
    template: 'schrodinger-packet',
  },
  'chaos-pendulum': { template: 'double-pendulum', description: '双摆初值敏感混沌运动' },
  'sierpinski-tri': { template: 'sierpinski-fold', description: '三角形反复挖空分形' },
  'zeeman-split': { template: 'spectral-split', description: '磁场中谱线塞曼劈裂' },
  'stark-effect': { template: 'spectral-split', description: '电场中谱线斯塔克移动' },
  'quantum-entangle': { template: 'entangled-pair', description: '纠缠粒子对关联运动' },
  'bell-inequality': { template: 'entangled-pair', description: '纠缠态违背贝尔不等式' },
  'reentry-arc': { template: 'reentry-blunt', description: '再入大气层加热减速下落' },
  'twin-paradox': { template: 'twin-clocks', description: '高速旅行者钟慢于地面钟' },
  'black-hole-shadow': { template: 'black-hole-shadow', description: '事件视界周围明亮吸积环阴影' },
  'time-dilation': { template: 'twin-clocks', description: '强引力场或高速运动时钟变慢' },
  'poisson-process': { template: 'poisson-arrivals', description: '稀有事件按泊松率到达' },
  'dark-matter-halo': { template: 'halo-envelope', description: '星系暗物质晕密度包络' },
  'pythagorean-tree': { description: '直角三角形递归分叉生长（示意）' },
  'mars-transfer': { description: '地球-火星霍曼最小能量转移轨道' },
  'standard-model': { description: '粒子物理标准模型多粒子示意' },
  'higgs-mechanism': { description: '希格斯场自发对称破缺（能级示意）' },
  'central-limit': { description: '样本均值分布趋近正态（钟形示意）' },
  'chi-square': { description: '卡方分布偏斜钟形（统计示意）' },
  't-distribution': { description: 't 分布厚尾钟形（统计示意）' },
  'bose-einstein': { description: '玻色子宏观量子凝聚（包络示意）' },
  'zeta-harmonic': {
    template: 'harmonic-series',
    description: 'Σ1/n 项递减但部分和持续攀升发散',
  },
  'power-series': {
    template: 'power-series-radius',
    description: 'Σaₙxⁿ 在收敛半径内逐项收敛',
  },
  'series-converge': {
    template: 'series-converge-limit',
    description: '部分和序列趋近稳定极限',
  },
  'fourier-sawtooth': { template: 'fourier-sawtooth', description: '锯齿波傅里叶合成' },
  'fourier-transform': {
    template: 'fourier-spectrum',
    description: '时域波形与频域谱线互转',
  },
  'chi-square': {
    template: 'chi-square-skew',
    description: '右偏卡方分布曲线（统计示意）',
  },
  't-distribution': {
    template: 't-distribution-wide',
    description: '厚尾 t 分布曲线（统计示意）',
  },
  'compton-scatter': { description: '光子-电子碰撞波长变长（频移示意）' },
  'three-body': { description: '三体引力混沌轨道（利萨如示意）' },
  'n-body-chaos': { description: 'N 体引力不可积混沌（参数轨道示意）' },
  'mandelbrot-orbit': { description: '复迭代 z²+c 轨道有界性探测' },
  'julia-set': { description: '朱利亚集边界迭代点逃逸' },
};

const GENERIC_TEMPLATE_HINTS = new Set<TemplateName>([
  'gaussian-bell',
  'logistic-curve',
  'light-cone',
  'orbit-ellipse',
  'hohmann-transfer',
  'energy-levels',
  'wave-interference',
  'doppler-shift',
  'redshift-spectrum',
  'exponential-decay',
  'bifurcation-fork',
  'bernoulli-flow',
  'stokes-circulation',
  'field-curl',
  'field-divergence',
  'accretion-disk',
  'brownian-motion',
  'lissajous',
  'orbit-circle',
  'projectile-arc',
  'heat-diffusion',
  'matrix-pulse',
  'fourier-bars',
  'taylor-series',
  'dirac-impulse',
  'standing-wave',
  'tunnel-barrier',
  'wave-packet',
  'schrodinger-packet',
  'action-integral',
  'regression-line',
  'markov-chain',
  'sine-wave',
]);

function applyCatalogFixes(catalog: IconDefinition[]): IconDefinition[] {
  return catalog.map((item) => {
    const fix = CATALOG_FIXES[item.id];
    let next = fix ? { ...item, ...fix } : { ...item };

    if (
      GENERIC_TEMPLATE_HINTS.has(next.template) &&
      !next.description.includes('示意')
    ) {
      next = { ...next, description: `${next.description}（动画示意）` };
    }

    return next;
  });
}

export const ICON_CATALOG: IconDefinition[] = applyCatalogFixes([
  ...preserved,
  ...generated,
  ...EXPANSION_CATALOG,
]);

const ICON_CATALOG_TARGET = 376;

if (ICON_CATALOG.length !== ICON_CATALOG_TARGET) {
  throw new Error(`ICON_CATALOG must contain ${ICON_CATALOG_TARGET} icons, got ${ICON_CATALOG.length}`);
}

export const PRESERVED_HAND_ICONS = PRESERVED_IDS;
